name: Protect README.md

on:
  push:
    branches:
      - main # Adjust if you're using a different branch

jobs:
  protect-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for changes to README.md
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q "README.md"; then
            echo "README.md has been modified. Reverting changes."
            git checkout HEAD^ -- README.md
            git add README.md
            git commit -m "Revert unwanted changes to README.md"
            git push
          else
            echo "README.md is unchanged."
          fi
