name: Remove README.md from Commits

on:
  push:
    branches:
      - main  # Specify the branch where you want to remove README.md

jobs:
  remove-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Remove README.md from commit
        run: |
          git rm --cached README.md || true
          git commit -m "Remove README.md from commit" || true
          git push origin HEAD || true
